name: zapgit

services:
  redis:
    image: redis
    ports: 
      - 6379:6379
  zapbackend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 8000:443
    secrets:
      - groq_key
  zapfrontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 8501:80

secrets:
  groq_key:
    environment: groq_api_key